- type: job
  parent: CMJobBase
  id: CMCivilianCorrespondent
  name: cm-job-name-civilian-correspondent
  description: cm-job-description-civilian-correspondent
  playTimeTracker: CMJobCivilianCorrespondent
  requirements:
  - !type:TotalDepartmentsTimeRequirement
    group: CMDepartmentsHuman
    time: 36000 # 10 hours
  ranks:
    RMCRankCivilian: []
  startingGear: CMGearCivilianCorrespondent
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - ColonyCorrespondent
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: RMCUserBulkyArmorIncapable
    - type: Skills
      skills:
        RMCSkillFirearms: 0
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: cm-job-prefix-correspondent
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: correspondent
    - type: RMCRibbon
  hasIcon: false
  hidden: true
  
- type: job
  parent: CMJobBase
  id: CMMilitaryCorrespondent
  name: cm-job-name-military-correspondent
  description: cm-job-description-military-correspondent
  playTimeTracker: CMJobMilitaryCorrespondent
  requirements:
  - !type:TotalDepartmentsTimeRequirement
    group: CMDepartmentsHuman
    time: 36000 # 10 hours
  ranks:
    RMCRankCorporal: []
  startingGear: CMGearMilitaryCorrespondent
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - CMCorrespondent
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 1   
    - type: JobPrefix
      prefix: cm-job-prefix-military-correspondent
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: correspondent
  hasIcon: false
  hidden: true
  
- type: job
  parent: CMCivilianCorrespondent
  id: CMCorrespondent
  name: cm-job-name-base-correspondent
  description: cm-job-description-base-correspondent
  playTimeTracker: CMJobCorrespondent
  jobVariants:
    - CMCivilianCorrespondent
    - CMMilitaryCorrespondent
  hasIcon: false
  hidden: false

- type: startingGear
  id: CMGearMilitaryCorrespondent
  equipment:
    head: RMCHeadCapFlippable
    jumpsuit: JumpsuitMarineWebbingBrown
    shoes: CMBootsBlackFilled
    id: CMDogtagCorrespondent
    ears: CMHeadsetReporter
    belt: RMCM1984BeltFilled
    pocket1: RMCPouchGeneralMedium
    pocket2: RMCPouchGeneralMedium
  inhand: 
  - RMCCameraBroadcasting

- type: startingGear
  id: CMGearCivilianCorrespondent
  equipment:
    jumpsuit: RMCJumpsuitCorrespondent
    outerClothing: RMCCoatCorrespondent
    shoes: RMCShoesLaceup
    id: CMIDCardCorrespondent
    ears: CMHeadsetReporter
    pocket1: RMCPouchGeneralLarge
    pocket2: RMCCorrespondentMicrophone
  inhand: 
  - RMCCameraBroadcasting  
  
- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCorrespondent
  name: correspondent spawn point
  components:
  - type: SpawnPoint
    job_id: CMCorrespondent
  - type: Sprite
    state: marine_spawn
    
#- type: entity
#  parent: CMSpawnPointJobBase
#  id: CMSpawnPointMilitaryCorrespondent
#  name: military correspondent spawn point
#  components:
#  - type: SpawnPoint
#    job_id: CMMilitaryCorrespondent
#  - type: Sprite
#    state: marine_spawn

#- type: entity
#  parent: CMSpawnPointJobBase
#  id: CMSpawnPointCivilianCorrespondent
#  name: civilian correspondent spawn point
#  components:
#  - type: SpawnPoint
#    job_id: CMCivilianCorrespondent
#  - type: Sprite
#    state: marine_spawn

- type: playTimeTracker
  id: CMJobCorrespondent
  isHumanoid: true
  
- type: playTimeTracker
  id: CMJobCivilianCorrespondent
  isHumanoid: true
  
- type: playTimeTracker
  id: CMJobMilitaryCorrespondent
  isHumanoid: true
